user: deploy
group: deploy
timeout: 30
wait: 30
log: logs/thin.log
max_conns: 1024
environment: production
max_persistent_conns: 512
port: 9292
threaded: true
no-epoll: true
daemonize: true
pid: tmp/pids/thin.pid
chdir: /var/www/transcoder-manager/current
tag: transcoder-manager
